<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="WIN-74F67QMA4MM" name="Test" tests="7" failures="1" timestamp="9 Apr 2018 13:43:02 GMT" time="2.445" errors="0">
  <testcase name="insertar" time="0.263" classname="pe.com.test.CategoriaTest"/>
  <testcase name="insertarConParametro" time="0.022" classname="pe.com.test.CategoriaTest"/>
  <testcase name="insertarDataProvider" time="0.034" classname="pe.com.test.CategoriaTest"/>
  <testcase name="insertarDataProvider" time="0.012" classname="pe.com.test.CategoriaTest"/>
  <testcase name="insertarDataProvider" time="0.008" classname="pe.com.test.CategoriaTest"/>
  <testcase name="metodoFueraDeTiempo" time="2.021" classname="pe.com.test.CategoriaTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.metodoFueraDeTiempo() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.metodoFueraDeTiempo() didn't finish within the time-out 2000
]]>
    </failure>
  </testcase> <!-- metodoFueraDeTiempo -->
  <testcase name="actualizar" time="0.042" classname="pe.com.test.CategoriaTest"/>
</testsuite> <!-- Test -->
